version: '3'

services:
  # php:7.2-apache
  php:
    build:
      context: ./php7.2
      dockerfile: dockerfile # php7.2/dockerfile. 本ファイルからイメージを作成
    volumes:
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf # バーチャルホスト設定
      - ./apache2/ports.conf:/etc/apache2/ports.conf                             # 起動ポート設定
      - ./php7.2/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8000:8080
# ↓更新がないとdocker落ちる…
#    command: ["/bin/bash", "-c", "cd /var/www/html && composer install"]
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webauthn
      - MYSQL_USER=webauthn
      - MYSQL_PASSWORD=webauthn
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=webauthn
      - PMA_PASSWORD=webauthn
    links:
      - mysql
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
  # Nginxのリバースプロキシ。自己証明書でphpコンテナをhttps化
  https-portal:
    image: steveltn/https-portal:1
    container_name: https_portal
    ports:
      - "80:80"
      - "443:443"
    tty: true
    restart: always
    volumes:
      - ./Certs/:/var/lib/https-portal/
    environment:
      DOMAINS: 'localhost.webauthndemo -> http://php:8080'
      STAGE: "local"
    links:
      - php