version: '3'

services:
  #################################################
  # PHP & Apache
  #################################################
  php-apache:
    build:
      context: ./php7.2
      dockerfile: dockerfile # php7.2/dockerfile. 本ファイルからイメージを作成
    container_name: php-apache
    volumes:
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf # バーチャルホスト設定
      - ./apache2/ports.conf:/etc/apache2/ports.conf                             # 起動ポート設定
      - ./php7.2/php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8000:8080
# ↓更新がないとdocker落ちる？よくわからん
#    command: ["/bin/bash", "-c", "cd /var/www/html && composer install"]
    links:
      - mysql:mysql
  #################################################
  # MySQL
  #################################################
  mysql:
    image: mysql:5.7
    #container_name: mysql57 # コンテナ名つけるとPHPからDBに接続できなくなる
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d # テーブル作成クエリ
      - ./mysql/data:/var/lib/mysql              # 物理データ
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webauthn
      - MYSQL_USER=webauthn
      - MYSQL_PASSWORD=webauthn
  #################################################
  # PhpMyAdmin
  #################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=webauthn
      - PMA_PASSWORD=webauthn
    links:
      - mysql
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
  #################################################
  # Nginx リバースプロキシ。自己証明書でphpコンテナをhttps化
  #################################################
  https-portal:
    image: steveltn/https-portal:1
    container_name: https_portal
    ports:
      - "80:80"
      - "443:443"
    tty: true
    restart: always
    volumes:
      - ./https-portal/Certs/:/var/lib/https-portal/ # 証明書
    environment:
      DOMAINS: 'localhost.webauthndemo -> http://php-apache:8080'
      STAGE: "local"
    links:
      - php-apache